---
Name: goldfinch-blocks
After:
  - '#elemental'
  - '#elementalcache'
---

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - Goldfinch\Blocks\Extensions\BaseElementExtension

DNADesign\ElementalList\Model\ElementList:
  icon: "bi-plugin"

DNADesign\ElementalVirtual\Model\ElementVirtual:
  icon: "bi-hypnotize"
