---
Name: goldfinch-blocks
After:
  - '#elemental'
  - '#elementalcache'
  - '#elemental-list'
  - '#elementalvirtual'
---

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - Goldfinch\Blocks\Extensions\BaseElementExtension

---
Name: goldfinch-blocks-icon
Only:
  moduleexists: 'goldfinch/enchantment'
---

DNADesign\ElementalList\Model\ElementList:
  icon: "bi-plugin"

DNADesign\ElementalVirtual\Model\ElementVirtual:
  icon: "bi-hypnotize"
